#!/usr/bin/env python3
"""
Refine the confidence gate using proper labels from gate_labels.json.

Usage on Colab:
    !python gpu/train_gate.py --base-checkpoint checkpoints/base/best.pt

Loads the base model (frozen fusion + prediction head), only trains θ_g.
Uses gate labels generated by scripts/04_generate_gate_labels.py.
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

from ttt.models import FullVQAModel
from ttt.data import VQADataset, vqa_collate_fn, load_answer_vocab
from ttt.utils import (
    load_config,
    load_checkpoint,
    save_checkpoint,
    load_json,
    setup_logging,
    get_device,
)


class GateLabelDataset(Dataset):
    """Dataset that wraps VQA dataset with gate labels."""

    def __init__(self, vqa_dataset, gate_labels_map):
        """
        Args:
            vqa_dataset: Base VQADataset instance.
            gate_labels_map: Dict mapping sample_id -> gate_label float.
        """
        self.vqa_dataset = vqa_dataset
        self.gate_labels_map = gate_labels_map

        # Filter samples that have gate labels
        self.valid_indices = []
        for i in range(len(vqa_dataset)):
            sample = vqa_dataset.samples[i]
            if sample["sample_id"] in gate_labels_map:
                self.valid_indices.append(i)

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        real_idx = self.valid_indices[idx]
        sample = self.vqa_dataset[real_idx]
        sample_id = self.vqa_dataset.samples[real_idx]["sample_id"]
        sample["gate_label"] = self.gate_labels_map[sample_id]
        return sample


def gate_collate_fn(batch):
    """Collate function for gate training."""
    base = vqa_collate_fn(batch)
    base["gate_labels"] = torch.tensor(
        [s["gate_label"] for s in batch], dtype=torch.float
    )
    return base


def main():
    parser = argparse.ArgumentParser(description="Train confidence gate")
    parser.add_argument("--config", type=str, default="config/config.yaml")
    parser.add_argument("--base-checkpoint", type=str, required=True)
    parser.add_argument("--epochs", type=int, default=None)
    args = parser.parse_args()

    config = load_config(args.config)
    device = get_device()
    logger = setup_logging("logs")

    epochs = args.epochs or config.get("gate_epochs", 5)
    batch_size = config.get("gate_batch_size", 128)
    lr = config.get("gate_lr", 5e-4)
    data_dir = config.get("data_dir", "data/")

    logger.info(f"Device: {device}")
    logger.info(f"Gate training: {epochs} epochs, batch={batch_size}, lr={lr}")

    # Load answer vocab
    answer_vocab = load_answer_vocab(os.path.join(data_dir, "answer_vocab.json"))

    # Create model and load base checkpoint
    model = FullVQAModel(config)
    model.load_encoders(config)
    load_checkpoint(model, args.base_checkpoint)
    model = model.to(device)
    logger.info(f"Loaded base checkpoint: {args.base_checkpoint}")

    # Freeze everything except gate
    for param in model.fusion.parameters():
        param.requires_grad = False
    for param in model.prediction_head.parameters():
        param.requires_grad = False
    for param in model.mask_proj.parameters():
        param.requires_grad = False
    for param in model.rotation_head.parameters():
        param.requires_grad = False

    gate_params = list(model.gate.parameters())
    trainable = sum(p.numel() for p in gate_params)
    logger.info(f"Gate trainable params: {trainable:,}")

    # Load gate labels
    gate_labels_path = os.path.join(data_dir, "gate_labels.json")
    gate_labels_raw = load_json(gate_labels_path)
    gate_labels_map = {item["sample_id"]: item["gate_label"] for item in gate_labels_raw}
    logger.info(f"Loaded {len(gate_labels_map)} gate labels")

    # Create dataset with gate labels
    val_dataset = VQADataset(
        questions_path=os.path.join(data_dir, "v2_OpenEnded_mscoco_val2014_questions.json"),
        annotations_path=os.path.join(data_dir, "v2_mscoco_val2014_annotations.json"),
        image_dir=os.path.join(data_dir, "val2014"),
        answer_vocab=answer_vocab,
        max_question_length=config.get("max_question_length", 20),
        image_size=config.get("image_size", 224),
        split="val",
    )

    gate_dataset = GateLabelDataset(val_dataset, gate_labels_map)
    logger.info(f"Gate training samples: {len(gate_dataset)}")

    # Split into train/val (80/20)
    train_size = int(0.8 * len(gate_dataset))
    val_size = len(gate_dataset) - train_size
    train_subset, val_subset = torch.utils.data.random_split(
        gate_dataset, [train_size, val_size]
    )

    train_loader = DataLoader(
        train_subset, batch_size=batch_size, shuffle=True,
        num_workers=4, pin_memory=True, collate_fn=gate_collate_fn,
    )
    val_loader = DataLoader(
        val_subset, batch_size=batch_size, shuffle=False,
        num_workers=4, pin_memory=True, collate_fn=gate_collate_fn,
    )

    # Optimizer — gate params only
    optimizer = torch.optim.Adam(gate_params, lr=lr)

    # Training loop
    best_val_loss = float("inf")
    checkpoint_dir = os.path.join(config.get("checkpoint_dir", "checkpoints/"), "gate")
    os.makedirs(checkpoint_dir, exist_ok=True)

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        num_batches = 0
        t0 = time.time()

        for batch in train_loader:
            images = batch["images"].to(device)
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            gate_labels = batch["gate_labels"].to(device)

            # Encode and fuse (no grad through frozen parts)
            with torch.no_grad():
                visual_tokens, text_tokens = model.encode(images, input_ids, attention_mask)
                z = model.fusion(visual_tokens, text_tokens, attention_mask)

            # Gate prediction (gradients only for gate)
            confidence = model.gate(z)
            loss = F.binary_cross_entropy(confidence.squeeze(-1), gate_labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            num_batches += 1

        elapsed = time.time() - t0
        avg_loss = epoch_loss / max(num_batches, 1)

        # Validation
        model.eval()
        val_loss = 0.0
        val_batches = 0
        with torch.no_grad():
            for batch in val_loader:
                images = batch["images"].to(device)
                input_ids = batch["input_ids"].to(device)
                attention_mask = batch["attention_mask"].to(device)
                gate_labels = batch["gate_labels"].to(device)

                visual_tokens, text_tokens = model.encode(images, input_ids, attention_mask)
                z = model.fusion(visual_tokens, text_tokens, attention_mask)
                confidence = model.gate(z)
                loss = F.binary_cross_entropy(confidence.squeeze(-1), gate_labels)

                val_loss += loss.item()
                val_batches += 1

        avg_val_loss = val_loss / max(val_batches, 1)
        logger.info(
            f"Epoch {epoch+1}/{epochs} ({elapsed:.0f}s) | "
            f"Train loss: {avg_loss:.4f} | Val loss: {avg_val_loss:.4f}"
        )

        # Save best
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            save_checkpoint(model, optimizer, epoch, os.path.join(checkpoint_dir, "best.pt"))
            logger.info(f"  New best gate checkpoint saved!")

    logger.info(f"\nGate training complete! Best val loss: {best_val_loss:.4f}")


if __name__ == "__main__":
    main()
